# Generated by Django 3.2.14 on 2022-07-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='publication_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('theme', models.CharField(choices=[('Report', 'Report'), ('Consultancy Files', 'Consultancy Files'), ('Research', 'Research'), ('Plans and Policies', 'Plans and Policies')], max_length=200)),
                ('publication_type', models.CharField(choices=[('Files', 'Files'), ('Audio', 'Audion'), ('Video', 'Video')], max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_picture', models.ImageField(upload_to='Pictures/')),
                ('author', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
                ('file_link', models.URLField()),
                ('published_date', models.DateTimeField(null=True)),
                ('language', models.CharField(choices=[('Nepali', 'Nepali'), ('English', 'English')], max_length=100)),
            ],
        ),
    ]
